create table public.credit_banks (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0),
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.credit_offers (
  id bigint generated by default as identity primary key,
  bank_id bigint not null references public.credit_banks(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  min_term_months integer not null check (min_term_months > 0),
  max_term_months integer not null check (max_term_months >= min_term_months),
  min_amount numeric(12, 2) not null check (min_amount > 0),
  max_amount numeric(12, 2) not null check (max_amount >= min_amount),
  interest_rate_type text not null default 'monthly_flat'
    check (interest_rate_type in ('monthly_flat', 'annual_nominal')),
  interest_rate numeric(7, 4) not null check (interest_rate >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index credit_banks_active_order_idx
on public.credit_banks (active, display_order, name);

create index credit_offers_bank_active_idx
on public.credit_offers (bank_id, active, name);

alter table public.credit_banks enable row level security;
alter table public.credit_offers enable row level security;

revoke all on table public.credit_banks from anon, authenticated;
revoke all on table public.credit_offers from anon, authenticated;
revoke all on sequence public.credit_banks_id_seq from anon, authenticated;
revoke all on sequence public.credit_offers_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.credit_banks to authenticated;
grant select, insert, update, delete on table public.credit_offers to authenticated;
grant usage, select on sequence public.credit_banks_id_seq to authenticated;
grant usage, select on sequence public.credit_offers_id_seq to authenticated;

create policy "Authenticated users can read credit banks"
on public.credit_banks for select
to authenticated
using (true);

create policy "Admins can create credit banks"
on public.credit_banks for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
);

create policy "Admins can update credit banks"
on public.credit_banks for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
);

create policy "Admins can delete credit banks"
on public.credit_banks for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
);

create policy "Authenticated users can read credit offers"
on public.credit_offers for select
to authenticated
using (true);

create policy "Admins can create credit offers"
on public.credit_offers for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
);

create policy "Admins can update credit offers"
on public.credit_offers for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
);

create policy "Admins can delete credit offers"
on public.credit_offers for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('owner', 'admin')
  )
);
