create table if not exists public.grant_settings (
  id smallint primary key default 1 check (id = 1),
  program_name text not null default 'Grant OZE — Radzionków',
  fixed_margin_gross numeric(12, 2) not null default 3000 check (fixed_margin_gross >= 0),
  min_pv_kw numeric(6, 3) not null default 2 check (min_pv_kw > 0),
  max_pv_kw numeric(6, 3) not null default 10 check (max_pv_kw >= min_pv_kw),
  annual_yield_kwh_per_kwp numeric(8, 2) not null default 1000 check (annual_yield_kwh_per_kwp > 0),
  heat_pump_extra_pv_kw numeric(6, 3) not null default 4 check (heat_pump_extra_pv_kw >= 0),
  pv_eligible_limit_gross numeric(12, 2) not null default 20000 check (pv_eligible_limit_gross >= 0),
  extra_pv_eligible_limit_gross numeric(12, 2) not null default 20000 check (extra_pv_eligible_limit_gross >= 0),
  pv_limit_gross_per_kwp numeric(12, 2) not null default 5000 check (pv_limit_gross_per_kwp >= 0),
  heat_pump_eligible_limit_gross numeric(12, 2) not null default 35000 check (heat_pump_eligible_limit_gross >= 0),
  combined_grant_limit_gross numeric(12, 2) not null default 55000 check (combined_grant_limit_gross >= 0),
  vat_rate numeric(5, 2) not null default 23 check (vat_rate >= 0),
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

insert into public.grant_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.grant_panels (
  id bigint generated by default as identity primary key,
  manufacturer text not null,
  model text not null,
  power_wp integer not null check (power_wp > 0),
  price_gross numeric(12, 2) not null default 0 check (price_gross >= 0),
  catalog_card_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grant_inverters (
  id bigint generated by default as identity primary key,
  manufacturer text not null,
  model text not null,
  power_kw numeric(6, 3) not null check (power_kw > 0),
  phase_count smallint not null default 3 check (phase_count in (1, 3)),
  price_gross numeric(12, 2) not null default 0 check (price_gross >= 0),
  catalog_card_url text,
  program_compliant boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grant_heat_pumps (
  id bigint generated by default as identity primary key,
  manufacturer text not null,
  model text not null,
  power_kw numeric(6, 3) not null check (power_kw > 0),
  pump_type text not null default 'monoblock' check (pump_type in ('monoblock', 'split')),
  price_gross numeric(12, 2) not null default 0 check (price_gross >= 0),
  cop numeric(5, 2) check (cop is null or cop > 0),
  zum_compliant boolean not null default false,
  zum_url text,
  catalog_card_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.grant_settings enable row level security;
alter table public.grant_panels enable row level security;
alter table public.grant_inverters enable row level security;
alter table public.grant_heat_pumps enable row level security;

create policy "Authenticated users can read grant settings"
on public.grant_settings for select
to authenticated
using (true);

create policy "Admins can manage grant settings"
on public.grant_settings for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('owner', 'admin')
  )
);

create policy "Authenticated users can read grant panels"
on public.grant_panels for select to authenticated using (true);
create policy "Admins can manage grant panels"
on public.grant_panels for all to authenticated
using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('owner', 'admin')))
with check (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('owner', 'admin')));

create policy "Authenticated users can read grant inverters"
on public.grant_inverters for select to authenticated using (true);
create policy "Admins can manage grant inverters"
on public.grant_inverters for all to authenticated
using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('owner', 'admin')))
with check (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('owner', 'admin')));

create policy "Authenticated users can read grant heat pumps"
on public.grant_heat_pumps for select to authenticated using (true);
create policy "Admins can manage grant heat pumps"
on public.grant_heat_pumps for all to authenticated
using (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('owner', 'admin')))
with check (exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('owner', 'admin')));
